### ISSUE TITLE
Settings aren’t stored after `Chome DevTools` reload

### ISSUE THREAD

**Issue by dimakuba** [rangle/angular-devtools#800] opened 2021-05-20 11:59 UTC
**Angular DevTools version:** 1.0.0

**Angular version:** 11.0.0

**OS:** macOS 11.3.1

**System theme:** Light

_Steps to reproduce:_

1. open `Chome DevTools` and navigate to `Angular` tab.

3. open settings and select `Dark Mode`.

4. close `Chome DevTools`.

5. open `Chome DevTools` and navigate to `Angular` tab.

6. open settings.

_Actual result:_ `Dark Mode` toggle is disabled.

_Expected result:_ `Dark Mode` toggle is enabled.

**Comment by mgechev** [comment] 2021-05-20 16:53
Duplicate of this feature request https://github.com/rangle/angular-devtools/issues/796

**Closed by mgechev** 2021-05-20 16:53 UTC
Labels: bug
