### ISSUE TITLE
Cannot inspect Angular Material Dialog component and its sub-components

### ISSUE THREAD

**Issue by tuanle07** [rangle/angular-devtools#852] opened 2021-06-10 16:52 UTC
**Angular DevTools version (required)**: 10.0.7

**Angular version (required):** 10.0.7

_Description of issue:_
Cannot inspect Angular Material Dialog component as well as any sub-components inside the dialog. The DevTools does not show anything related to the dialog at all.

_Additional details:_
Angular Material Dialog: https://material.angular.io/components/dialog/overview

**Comment by AleksanderBodurri** [comment] 2021-06-10 17:02
Looks like a duplicate of #791

If possible, upgrading to Angular v12 should resolve this issue.

Gonna close this for now. Let me know if you have any concerns

**Closed by AleksanderBodurri** 2021-06-10 17:02 UTC
Labels: bug
