### ISSUE TITLE
___devToolsContentScript is not defined

### ISSUE THREAD

**Issue by sroucheray** [rangle/angular-devtools#787] opened 2021-05-19 12:05 UTC
_Description:_
When opening the devtools on a locally served angular application page, the console shows the following error `___devToolsContentScript is not defined`

Also the extension does not detect the application either in the devtools nor in the extension icon. 
...

**Angular Devtools version (required)**:
1.0.0
**Angular version (required):**
10.2.3
**Date:**
19/05/2021
**OS:**
Ubuntu

![image](https://user-images.githubusercontent.com/169818/118809309-c096ee00-b8aa-11eb-980c-11f8f24f73c5.png)

**Comment by mgechev** [comment] 2021-05-19 12:23
Could you share a sample app where we can reproduce the problem?

**Comment by elektronik2k5** [comment] 2021-05-19 13:13
Happens to me too with the very same version: `angular@10.2.3`.

**Comment by sroucheray** [comment] 2021-05-20 11:56
@elektronik2k5 I had tried to even completely restart the browser after the extension installation but it still does not work for me, failing with the same error.

@mgechev Unfortunately my app is in a private repo, I should test with another app when I have more time.

**Comment by mgechev** [comment] 2021-05-23 18:13
@sroucheray thanks! Let me know if you get a chance to prepare a reproduction.

**Comment by mgechev** [comment] 2021-06-01 19:41
In case you're still able to reproduce this error, please follow up in another issue and share a minimal demo. Closing for now because we don't have steps to move forward with a fix.

**Closed by mgechev** 2021-06-01 19:41 UTC
Labels: bug, needs clarification
