### ISSUE TITLE
Persist Dark Mode 

### ISSUE THREAD

**Issue by yuwu9145** [rangle/angular-devtools#796] opened 2021-05-20 03:17 UTC
**What feature do you want to see?**
Persist Dark mode.

**Why is it important to you?**
Every time when app is reloaded, dev tool rolls back to default light theme color, which requires to manually re-enable dark model. It would be handy to have it enabled once and persists afterwards

**Describe functionality in details. Apply mocks if applicable:**

Make dark mode persist so users do not have to consistently re-enable it after each app re-load after re-compile

**Comment by vugar005** [comment] 2021-05-21 09:05
This is duplicate of [#775](https://github.com/rangle/angular-devtools/issues/775)

**Comment by mgechev** [comment] 2021-05-21 17:39
@vugar005 thanks for pointing this out!

**Closed** 2021-05-21 17:39 UTC
Labels: feature
