### ISSUE TITLE
DevTools does not show component tree when injecting ViewContainerRef in AppComponent

### ISSUE THREAD

**Issue by decline** [rangle/angular-devtools#824] opened 2021-05-27 10:13 UTC
**Angular DevTools version (required)**: 1.0.1

**Angular version (required):** 11.2.14

**Link to a minimal GitHub repository:** https://github.com/decline/angular-devtools-issue

_Description of issue:_ 

When injecting the ViewContainerRef in the AppComponent construct, Angular DevTools will not work.

To make it work again, remove this construct from the AppComponent:

```ts
  constructor(public viewContainerRef: ViewContainerRef) {
    this.hasViewContainerRef = !!viewContainerRef;
  }
```

_Steps to reproduce:_

1. Checkout GitHub repository, run `npm install` and serve app with `ng serve`

2. Open the app in the browser and start DevTools (you should **not** see the component tree in DevTools):
<img width="903" alt="Screen Shot 2021-05-27 at 12 10 34" src="https://user-images.githubusercontent.com/5609744/119808656-a087b000-bee4-11eb-98f8-e5597027463b.png">

3. In `AppComponent` just remove the construct. DevTools should now show the component tree:
<img width="904" alt="Screen Shot 2021-05-27 at 12 10 52" src="https://user-images.githubusercontent.com/5609744/119808800-c4e38c80-bee4-11eb-9c67-233888600e7c.png">

**Comment by mgechev** [comment] 2021-05-27 21:43
Duplicate of https://github.com/rangle/angular-devtools/issues/773 and https://github.com/rangle/angular-devtools/issues/809. The easiest fix would be to update to v12.

**Closed by mgechev** 2021-05-27 21:43 UTC
Labels: bug
