### ISSUE TITLE
This page is not using Angular, or it has a strict extension policy.

### ISSUE THREAD

**Issue by AshMcConnell** [rangle/angular-devtools#780] opened 2021-05-19 08:02 UTC
I get the error `This page is not using Angular, or it has a strict extension policy.` when trying to load the dev tools

**Angular Devtools version (required)**:
1.0.0
**Angular version (required):**
10.1.4
**Date:**
18 May 2021
**OS:**
Windows 10 64bit

_Description of issue:_

Angular isn't detected, not sure what other info is available.  It is served using `ng serve`
![image](https://user-images.githubusercontent.com/497941/118777212-b6f89080-b880-11eb-9be6-474ea5ab65eb.png)

**Comment by joguarino** [comment] 2021-05-19 09:41
Same problem, but I noticed that opening Chrome DevTools the tab "Angular" is correctly shown and working

![image](https://user-images.githubusercontent.com/11157140/118791513-0fd32380-b897-11eb-88a4-e27ef82d1432.png)

**Comment by pete-mcwilliams** [comment] 2021-05-19 09:47
On installing the extension in chrome where a tab had already loaded the angular page then selecting the angular tab I was seeing the issues mentioned here.  I also had a debugger window already open on that tab.

Closing the debugger window and the tab, in same chrome window added a new tab and navigated to the angular application, the extension recognised angular.

**Comment by mgechev** [comment] 2021-05-19 12:29
Thank you for the report! We'll look into this.

**Comment by AshMcConnell** [comment] 2021-05-19 12:41
@mgechev Great, thanks - it looks awesome.  I eventually got it working from the comments above (thanks folks!), but unfortunately my hierarchy is nested quite a bit and I can't see components in the tree that are down more than 3-4 levels.  Is there any way to tweak that setting?

**Comment by mgechev** [comment] 2021-05-19 12:44
Make sure you update to v12 to use the newest debugging APIs we introduced. If the problem persists, please open a bug fix here with a minimal repo. :)

**Comment by AshMcConnell** [comment] 2021-05-19 13:07
Ah ok, it'll probably be 6 months until we can move from 10, but something to look forward to :).  Thanks again!

**Comment by Hedva** [comment] 2021-05-19 13:37
Had the same issue as described above, with Angular 11.1.1 and Chrome 90.0.4430.212, running from Visual Studio Professional 2019 (16.9.6)

Tab is working fine but the extension button gives a error message.

**Comment by mgechev** [comment] 2021-05-19 17:34
Just to confirm, looks like the problem is that the popup shows there's no Angular on the page, but you can inspect the component tree and use the profiler in DevTools. Is that correct?

**Comment by yngvebn** [comment] 2021-05-19 17:41
> Just to confirm, looks like the problem is that the popup shows there's no Angular on the page, but you can inspect the component tree and use the profiler in DevTools. Is that correct?

I get this problem, and I'm not able to use the tree nor the profiler. It doesn't show any errors either - just a blank window.
![image](https://user-images.githubusercontent.com/772071/118859157-336b8d80-b8da-11eb-9ebc-faecea7a2783.png)

**Comment by mgechev** [comment] 2021-05-19 17:59
@yngvebn could you share a minimal demo where we can reproduce the problem?

**Comment by yngvebn** [comment] 2021-05-19 18:00
> @yngvebn could you share a minimal demo where we can reproduce the problem?

I wish I could, but the project is far from minimal 😅  I'll see if I can reproduce it in a fresh project tomorrow 👍

**Comment by mgechev** [comment] 2021-05-19 22:11
Looks like there are at least three different issues folks have been reporting in this thread:

- The "Angular" tab in DevTools not showing if the extension is installed while Chrome DevTools is already open. There's nothing we can do about this on the Angular side, unfortunately
- Empty component tree. That's wrong and we need to fix it. Please share a minimal demo where we can reproduce the problem. That's a high-priority problem we need to look into
- The extension showing the app is not using Angular. Could you share more details? Did you try it on a production application? Could you share a minimal demo that allows us to reproduce the problem?

**Comment by prewk** [comment] 2021-05-20 10:53
Here's another contender: Button shows as OP, opening the Angular devtool tab starts to spin up the extension, but then crashes with this error in the console: `Uncaught TypeError: Cannot read property 'getDirectiveMetadata' of undefined`.

If it helps, the pretty printed stack trace points out where the error occurs:

![image](https://user-images.githubusercontent.com/640102/118966812-4332b280-b96a-11eb-8bce-ba07761b010f.png)

**Comment by mgechev** [comment] 2021-05-23 18:11
@prewk this seems like a different issue. Thanks for the stack trace! Could you share a minimal reproduction in a separate issue where we can investigate and push a fix?

**Comment by mgechev** [comment] 2021-05-23 18:12
To go back to the original problem:

>I get the error This page is not using Angular, or it has a strict extension policy. when trying to load the dev tools

Are you still getting this problem after following the steps by @pete-mcwilliams?

>On installing the extension in chrome where a tab had already loaded the angular page then selecting the angular tab I was seeing the issues mentioned here. I also had a debugger window already open on that tab.
>
>Closing the debugger window and the tab, in same chrome window added a new tab and navigated to the angular application, the extension recognised angular.

If anyone still sees this problem, could they share a minimal reproduction? Alternatively, we can close this issue and investigate the two separate problems that @prewk and @yngvebn reported.

**Comment by prewk** [comment] 2021-05-23 18:13
I would love to but essentially I'm in the same boat as many others... enormous app. But if I find the time maybe I can reduce it to a shred and find something 👍

**Comment by yngvebn** [comment] 2021-05-23 18:14
@mgechev I'll try to get a repro up and running in the next few days!

**Comment by mgechev** [comment] 2021-05-23 18:15
@prewk you might be able to reproduce this relatively easy by leaving only the `AppComponent` in your app and replacing its template with just a text node. The problem you reported seems to be in the initialization of the extension so what's more interesting is how you build the app - what flags are you using and how does your development build looks like.

**Comment by prewk** [comment] 2021-05-23 18:16
Great idea, I'll see what I can do!

**Comment by mgechev** [comment] 2021-05-23 18:16
@yngvebn thank you! Feel free to follow up in [this issue](https://github.com/rangle/angular-devtools/issues/809) because it seems related to what you're experiencing.

**Comment by mgechev** [comment] 2021-05-28 03:34
Just to follow up on this thread, do you have a steps that will allow us to reproduce `This page is not using Angular, or it has a strict extension policy.`?

**Comment by mgechev** [comment] 2021-05-28 04:21
We believe https://github.com/rangle/angular-devtools/pull/827 resolves the issue. I'll close and publish as part of 1.0.2. If the problem persists, please open a new issue.

**Closed by mgechev** 2021-05-28 04:21 UTC
Labels: P1, bug

**Comment by prewk** [comment] 2021-05-28 11:41
Cool, I tried reducing our webapp to nothing but one component but didn't allocate enough time so I gave up fightning our set-up that cried about it. Looking forward to trying out your fix.

**Comment by zeljkoantich** [comment] 2021-05-28 13:56
I'm hitting this on Linux also: `Linux Mint 20 Cinnamon`.

**Comment by mauriciogracia** [comment] 2021-06-01 15:10
> 
> 
> On installing the extension in chrome where a tab had already loaded the angular page then selecting the angular tab I was seeing the issues mentioned here. I also had a debugger window already open on that tab.
> 
> Closing the debugger window and the tab, in same chrome window added a new tab and navigated to the angular application, the extension recognised angular.

Thanks for posting this, it solved the issue.
