### ISSUE TITLE
Components pane is empty

### ISSUE THREAD

**Issue by hinok** [rangle/angular-devtools#809] opened 2021-05-21 10:07 UTC
**Angular DevTools version (required)**: `1.0.0`

**Angular version (required):** `11.2.11`

**Link to a minimal stackblitz reproduction (strongly encouraged):** `N/A`

_Description of issue:_

- Components pane is empty

![Screenshot 2021-05-21 at 11 57 30](https://user-images.githubusercontent.com/1313605/119120562-b7ce2580-ba2c-11eb-8f8a-63af65ea4b75.png)

_Steps to reproduce:_

1. Open page

2. Open dev tools

_Additional details:_

Components pane is empty but when I use `inspector`

<img width="689" alt="Screenshot 2021-05-21 at 12 04 44" src="https://user-images.githubusercontent.com/1313605/119120633-ca485f00-ba2c-11eb-9a89-f70921c52f23.png">

I can see small "tooltips" with components names like below

![Screenshot 2021-05-21 at 12 07 14](https://user-images.githubusercontent.com/1313605/119120892-16939f00-ba2d-11eb-88cd-65f043656694.png)

**Comment by guidopontet** [comment] 2021-05-21 12:39
Same here

```
Angular DevTools version (required): 1.0.0

Angular version (required): 11.0.2
```

**Comment by nikhilgrag** [comment] 2021-05-21 12:54
@hinok @guidopontet It was happening for me as well. Check your chrome console, if you are getting a warning `Unbale to find ID of undefined` when you try to inspect some element,
then you can refer to https://github.com/rangle/angular-devtools/issues/774

**Comment by mgechev** [comment] 2021-05-21 17:37
@hinok @guidopontet would you check updating to v12? We introduced better integration with framework which should fix the issue.

**Comment by mgechev** [comment] 2021-05-23 18:05
@hinok @nikhilgrag could you share a minimal reproduction so we can investigate and fix for older versions?

**Comment by nikhilgrag** [comment] 2021-05-24 03:09
@mgechev https://github.com/nikhilgrag/angular-dev-tools-old-version-error
It will start working once you remove ViewContainerRef from app.component.ts

**Comment by guidopontet** [comment] 2021-05-26 14:02
@mgechev start working ok on angular 12 update. ¡Thanks!

**Comment by mgechev** [comment] 2021-06-01 19:41
Closing it as duplicate of https://github.com/rangle/angular-devtools/issues/773.

**Closed by mgechev** 2021-06-01 19:41 UTC
Labels: bug
